# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensync2_plugin_kit/ipc_worker/transport.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sensync2_plugin_kit/ipc_worker/transport.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.sensync2_plugin_kit/ipc_worker/transport.proto\x12\x1esensync2_plugin_kit.ipc_worker\"J\n\x05Ready\x12\x18\n\x10protocol_version\x18\x01 \x01(\r\x12\x16\n\x0eworker_version\x18\x02 \x01(\t\x12\x0f\n\x07methods\x18\x03 \x03(\t\">\n\x07Request\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\",\n\x0bWorkerError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"w\n\x08Response\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\n\n\x02ok\x18\x02 \x01(\x08\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12:\n\x05\x65rror\x18\x04 \x01(\x0b\x32+.sensync2_plugin_kit.ipc_worker.WorkerError\"\n\n\x08Shutdown\"\x85\x02\n\x08\x45nvelope\x12\x36\n\x05ready\x18\x01 \x01(\x0b\x32%.sensync2_plugin_kit.ipc_worker.ReadyH\x00\x12:\n\x07request\x18\x02 \x01(\x0b\x32\'.sensync2_plugin_kit.ipc_worker.RequestH\x00\x12<\n\x08response\x18\x03 \x01(\x0b\x32(.sensync2_plugin_kit.ipc_worker.ResponseH\x00\x12<\n\x08shutdown\x18\x04 \x01(\x0b\x32(.sensync2_plugin_kit.ipc_worker.ShutdownH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensync2_plugin_kit.ipc_worker.transport_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READY']._serialized_start=82
  _globals['_READY']._serialized_end=156
  _globals['_REQUEST']._serialized_start=158
  _globals['_REQUEST']._serialized_end=220
  _globals['_WORKERERROR']._serialized_start=222
  _globals['_WORKERERROR']._serialized_end=266
  _globals['_RESPONSE']._serialized_start=268
  _globals['_RESPONSE']._serialized_end=387
  _globals['_SHUTDOWN']._serialized_start=389
  _globals['_SHUTDOWN']._serialized_end=399
  _globals['_ENVELOPE']._serialized_start=402
  _globals['_ENVELOPE']._serialized_end=663
# @@protoc_insertion_point(module_scope)
