import { EventTypes } from './event-types.ts';
import type { RuntimeEventMapCodegenSpec } from './runtime-event-map-codegen.ts';

export const sharedRuntimeEventMapSpec: RuntimeEventMapCodegenSpec = {
  moduleToAugment: './events.ts',
  coreImportPath: './events.ts',
  outputFilePath: 'packages/core/src/generated-runtime-event-map.ts',
  entries: [
    {
      alias: 'SignalBatchRuntimeEvent',
      mode: 'reference',
      type: EventTypes.signalBatch,
      v: 1,
      importPath: './events.ts',
      typeName: 'SignalBatchEvent',
    },
    {
      alias: 'AdapterScanRequestEvent',
      mode: 'compose',
      envelope: 'command',
      type: EventTypes.adapterScanRequest,
      v: 1,
      kind: 'command',
      priority: 'control',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'AdapterScanRequestPayload' },
    },
    {
      alias: 'AdapterScanStateChangedEvent',
      mode: 'compose',
      envelope: 'fact',
      type: EventTypes.adapterScanStateChanged,
      v: 1,
      kind: 'fact',
      priority: 'system',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'AdapterScanStateChangedPayload' },
    },
    {
      alias: 'AdapterScanCandidatesEvent',
      mode: 'compose',
      envelope: 'fact',
      type: EventTypes.adapterScanCandidates,
      v: 1,
      kind: 'fact',
      priority: 'system',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'AdapterScanCandidatesPayload' },
    },
    {
      alias: 'AdapterConnectRequestEvent',
      mode: 'compose',
      envelope: 'command',
      type: EventTypes.adapterConnectRequest,
      v: 1,
      kind: 'command',
      priority: 'control',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'AdapterConnectRequestPayload' },
    },
    {
      alias: 'AdapterDisconnectRequestEvent',
      mode: 'compose',
      envelope: 'command',
      type: EventTypes.adapterDisconnectRequest,
      v: 1,
      kind: 'command',
      priority: 'control',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'AdapterDisconnectRequestPayload' },
    },
    {
      alias: 'AdapterStateChangedEvent',
      mode: 'compose',
      envelope: 'fact',
      type: EventTypes.adapterStateChanged,
      v: 1,
      kind: 'fact',
      priority: 'system',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'AdapterStateChangedPayload' },
    },
    {
      alias: 'SimulationPauseRequestEvent',
      mode: 'compose',
      envelope: 'command',
      type: EventTypes.simulationPauseRequest,
      v: 1,
      kind: 'command',
      priority: 'control',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'SimulationPauseRequestPayload' },
    },
    {
      alias: 'SimulationResumeRequestEvent',
      mode: 'compose',
      envelope: 'command',
      type: EventTypes.simulationResumeRequest,
      v: 1,
      kind: 'command',
      priority: 'control',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'SimulationResumeRequestPayload' },
    },
    {
      alias: 'SimulationSpeedSetRequestEvent',
      mode: 'compose',
      envelope: 'command',
      type: EventTypes.simulationSpeedSetRequest,
      v: 1,
      kind: 'command',
      priority: 'control',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'SimulationSpeedSetRequestPayload' },
    },
    {
      alias: 'SimulationStateChangedEvent',
      mode: 'compose',
      envelope: 'fact',
      type: EventTypes.simulationStateChanged,
      v: 1,
      kind: 'fact',
      priority: 'system',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'SimulationStateChangedPayload' },
    },
    {
      alias: 'RecordingStartEvent',
      mode: 'compose',
      envelope: 'command',
      type: EventTypes.recordingStart,
      v: 1,
      kind: 'command',
      priority: 'control',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'RecordingStartPayload' },
    },
    {
      alias: 'RecordingStopEvent',
      mode: 'compose',
      envelope: 'command',
      type: EventTypes.recordingStop,
      v: 1,
      kind: 'command',
      priority: 'control',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'RecordingStopPayload' },
    },
    {
      alias: 'RecordingPauseEvent',
      mode: 'compose',
      envelope: 'command',
      type: EventTypes.recordingPause,
      v: 1,
      kind: 'command',
      priority: 'control',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'RecordingPausePayload' },
    },
    {
      alias: 'RecordingResumeEvent',
      mode: 'compose',
      envelope: 'command',
      type: EventTypes.recordingResume,
      v: 1,
      kind: 'command',
      priority: 'control',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'RecordingResumePayload' },
    },
    {
      alias: 'RecordingStateChangedEvent',
      mode: 'compose',
      envelope: 'fact',
      type: EventTypes.recordingStateChanged,
      v: 1,
      kind: 'fact',
      priority: 'system',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'RecordingStateChangedPayload' },
    },
    {
      alias: 'RecordingErrorEvent',
      mode: 'compose',
      envelope: 'fact',
      type: EventTypes.recordingError,
      v: 1,
      kind: 'fact',
      priority: 'system',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'RecordingErrorPayload' },
    },
    {
      alias: 'ShapeGenerateRequestEvent',
      mode: 'compose',
      envelope: 'command',
      type: EventTypes.shapeGenerateRequest,
      v: 1,
      kind: 'command',
      priority: 'control',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'ShapeGenerateRequestPayload' },
    },
    {
      alias: 'ShapeGeneratedEvent',
      mode: 'compose',
      envelope: 'fact',
      type: EventTypes.shapeGenerated,
      v: 1,
      kind: 'fact',
      priority: 'control',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'ShapeGeneratedPayload' },
    },
    {
      alias: 'LabelMarkRequestEvent',
      mode: 'compose',
      envelope: 'command',
      type: EventTypes.labelMarkRequest,
      v: 1,
      kind: 'command',
      priority: 'control',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'LabelMarkRequestPayload' },
    },
    {
      alias: 'TimelineResetRequestEvent',
      mode: 'compose',
      envelope: 'command',
      type: EventTypes.timelineResetRequest,
      v: 1,
      kind: 'command',
      priority: 'control',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'TimelineResetRequestPayload' },
    },
    {
      alias: 'CommandRejectedEvent',
      mode: 'compose',
      envelope: 'fact',
      type: EventTypes.commandRejected,
      v: 1,
      kind: 'fact',
      priority: 'system',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'CommandRejectedPayload' },
    },
    {
      alias: 'ActivityStateChangedEvent',
      mode: 'compose',
      envelope: 'fact',
      type: EventTypes.activityStateChanged,
      v: 1,
      kind: 'fact',
      priority: 'system',
      payload: { kind: 'inline', typeText: '{ active: boolean }' },
    },
    {
      alias: 'RuntimeStartedEvent',
      mode: 'compose',
      envelope: 'fact',
      type: EventTypes.runtimeStarted,
      v: 1,
      kind: 'fact',
      priority: 'system',
      payload: { kind: 'named', importPath: './events.ts', typeName: 'RuntimeStartedPayload' },
    },
    {
      alias: 'RuntimeTelemetrySnapshotEvent',
      mode: 'compose',
      envelope: 'fact',
      type: EventTypes.runtimeTelemetrySnapshot,
      v: 1,
      kind: 'fact',
      priority: 'system',
      payload: { kind: 'named', importPath: './ui.ts', typeName: 'RuntimeTelemetrySnapshotPayload' },
    },
    {
      alias: 'UiClientConnectedEvent',
      mode: 'compose',
      envelope: 'fact',
      type: EventTypes.uiClientConnected,
      v: 1,
      kind: 'fact',
      priority: 'system',
      payload: { kind: 'named', importPath: './ui.ts', typeName: 'UiClientConnectedPayload' },
    },
    {
      alias: 'UiClientDisconnectedEvent',
      mode: 'compose',
      envelope: 'fact',
      type: EventTypes.uiClientDisconnected,
      v: 1,
      kind: 'fact',
      priority: 'system',
      payload: { kind: 'named', importPath: './ui.ts', typeName: 'UiClientDisconnectedPayload' },
    },
    {
      alias: 'UiControlOutEvent',
      mode: 'compose',
      envelope: 'fact',
      type: EventTypes.uiControlOut,
      v: 1,
      kind: 'fact',
      priority: 'system',
      payload: { kind: 'named', importPath: './ui.ts', typeName: 'UiControlOutPayload' },
    },
    {
      alias: 'UiBinaryOutEvent',
      mode: 'compose',
      envelope: 'fact',
      type: EventTypes.uiBinaryOut,
      v: 1,
      kind: 'fact',
      priority: 'system',
      payload: { kind: 'named', importPath: './ui.ts', typeName: 'UiBinaryOutPayload' },
    },
  ],
};
