import type { RuntimeEventMapCodegenSpec } from '@sensync2/core';

export const trignoRuntimeEventMapSpec: RuntimeEventMapCodegenSpec = {
  moduleToAugment: '@sensync2/core',
  coreImportPath: '@sensync2/core',
  outputFilePath: 'packages/plugins-trigno/src/generated-runtime-event-map.ts',
  entries: [
    {
      alias: 'TrignoStreamStartRequestEvent',
      mode: 'compose',
      envelope: 'command',
      type: 'trigno.stream.start.request',
      v: 1,
      kind: 'command',
      priority: 'control',
      payload: { kind: 'named', importPath: './trigno-boundary.ts', typeName: 'TrignoCommandRequestPayload' },
    },
    {
      alias: 'TrignoStreamStopRequestEvent',
      mode: 'compose',
      envelope: 'command',
      type: 'trigno.stream.stop.request',
      v: 1,
      kind: 'command',
      priority: 'control',
      payload: { kind: 'named', importPath: './trigno-boundary.ts', typeName: 'TrignoCommandRequestPayload' },
    },
    {
      alias: 'TrignoStatusRefreshRequestEvent',
      mode: 'compose',
      envelope: 'command',
      type: 'trigno.status.refresh.request',
      v: 1,
      kind: 'command',
      priority: 'control',
      payload: { kind: 'named', importPath: './trigno-boundary.ts', typeName: 'TrignoCommandRequestPayload' },
    },
    {
      alias: 'TrignoStatusReportedEvent',
      mode: 'compose',
      envelope: 'fact',
      type: 'trigno.status.reported',
      v: 1,
      kind: 'fact',
      priority: 'system',
      payload: { kind: 'named', importPath: './trigno-boundary.ts', typeName: 'TrignoStatusReportedPayload' },
    },
    {
      alias: 'TrignoPollEvent',
      mode: 'compose',
      envelope: 'fact',
      type: 'trigno.poll',
      v: 1,
      kind: 'fact',
      priority: 'system',
      payload: { kind: 'inline', typeText: 'Record<string, never>' },
    },
  ],
};
